/**
 * #366: Assign Members When Creating a CalendarEvent.
 *
 * Stores which Members should be automatically reserved (via the existing
 * calendar_event_bookings mechanism, force=true) on every CalendarEvent
 * occurrence materialized by a recurring activity_type_schedule_rules row.
 * A Member is assigned to the rule, not to any single occurrence — new
 * occurrences generated by materializeScheduleRule() pick up the same set.
 *
 * Every step is guarded independently — DDL is non-transactional in MySQL,
 * so a retry after a partial failure must be able to resume.
 */
exports.up = async (knex) => {
  if (!(await knex.schema.hasTable('activity_type_schedule_rule_members'))) {
    await knex.schema.createTable('activity_type_schedule_rule_members', (t) => {
      t.increments('id').unsigned().primary();

      t.string('gym_id', 36).notNullable()
        .references('id').inTable('gyms').onDelete('CASCADE');

      t.integer('schedule_rule_id').unsigned().notNullable()
        .references('id').inTable('activity_type_schedule_rules').onDelete('CASCADE');

      t.integer('member_id').unsigned().notNullable()
        .references('id').inTable('members').onDelete('CASCADE');

      t.datetime('created_at').notNullable().defaultTo(knex.fn.now());

      t.index(['gym_id', 'schedule_rule_id'], 'atsrm_gym_rule_idx');
      t.index(['gym_id', 'member_id'], 'atsrm_gym_member_idx');
    });
  }

  const [uniqRows] = await knex.raw(
    "SHOW INDEX FROM activity_type_schedule_rule_members WHERE Key_name = 'atsrm_rule_member_unique'",
  );
  if (uniqRows.length === 0) {
    await knex.raw(
      'ALTER TABLE activity_type_schedule_rule_members ' +
      'ADD UNIQUE KEY atsrm_rule_member_unique (schedule_rule_id, member_id)',
    );
  }
};

exports.down = async (knex) => {
  await knex.schema.dropTableIfExists('activity_type_schedule_rule_members');
};
